services:
  - type: web
    name: gbtnetwork-bootnode
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DATADIR
        value: /root/.bootnode
    healthCheckPath: /static-nodes.json
    disk:
      name: bootnode-data
      mountPath: /root/.bootnode
      sizeGB: 1
